version: '3.8'

services:
  jupyterlab:
    image: ghcr.io/folinimarc/pretty_panda/processing_env-dev:2023-12-16-11-58-10
    working_dir: /workspace
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
