
name: Build and Push Dev

on:
  push:
    paths:
      - 'processingEnv/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./processingEnv
          push: true
          tags: ghcr.io/${{ github.repository }}/geo-processing-env:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          target: dev
